export const COUNT_INCREMENT = "COUNT_INCREMENT";
export const COUNT_DECREMENT = "COUNT_DECREMENT";
export const COUNT_INCREMENT_NUMBER = "COUNT_INCREMENT_NUMBER";
export const COUNT_DECREMENT_NUMBER = "COUNT_DECREMENT_NUMBER";
export const COUNT_RESET = "COUNT_RESET";
